const router = require('express').Router();

const firstAscents = {
    head : ["Date", "Name/Climber(s)/Description", "Grade", "Location"],
    body : [
        ["1912, Jun","Route 1","Moderate","Sheepbone Buttress"],
        ["","C.A. Elliott and party","",""],
        ["1912, Jun","Route 2","Difficult","Sheepbone Buttress"],
        ["","C.A. Elliott and party","",""],
        ["1912","Mitre Buttress Ordinary","Moderate","Grey Crag, Buttermere"],
        ["","C.A. Elliott and party","",""],
        ["1913, Dec","The Barn Door","Moderate","Eagle Crag"],
        ["","A.C. Pigou and party","",""],
        ["1915, 4 Jul","Mitre Buttress Direct","Very Difficult","Grey Crag, Buttermere"],
        ["","A.C. Pigou and party","",""],
        ["1927, Mar","Arete and Slab Climb","Difficult","Bochlwyd Buttress"],
        ["","C.H.S.R. Palmer","",""],
        ["1927, Apr","Alpha-Beta Route","","Glyder Fach"],
        ["","H.G. Wager, P. Lloyd, B.K. Harris","",""],
        ["1927, 14 May","Long Chimney Pitch 1","HS 4b","East Face of Tryfan"],
        ["","Ivan M. Waller","",""],
        ["","Technically the crux pitch","",""],
        ["1927, 7 Jun","Belle Vue Bastion","VS","Tryfan"],
        ["","Ivan Waller, C.H.S.R. Palmer","",""],
        ["1927, 11 Sep","Fallen Block Crack","VS","Clogwyn-y-Ddisgl"],
        ["","Ivan Waller","",""],
        ["1928, 28 May","West Buttress","VS","Clogwyn d'ur Arddhu"],
        ["","J.L. Longland, A.S. Pigott, F.S. Smythe, W. Eversden, Morley Wood","",""],
        ["1928, Jun","Birch Tree Wall","VS 5a","Black Rocks"],
        ["","Jack Longland, Ivan Waller","",""],
        ["","The tree was originally indentified as a beech - by a future Director of Education. The tree subsequently disappeared in 1950.","",""],
        ["1928, Jul","Lone Tree Groove","VS 4c","Black Rocks"],
        ["","Ivan Waller","",""],
        ["","An ice axe was used to remove huge quantities of turf prior to the first ascent. Ivan was disappointed to reveal 'just an ordinary boot climb, quite long and interesting, but not at all difficult except at the start.' The route was originally called The Scoop and the Sine Nomine Exit (Ivan Waller July 1929) left it on the right.","",""],
        ["1928","Purgatory Route","","Lliwedd"],
        ["","Jack Longland, L.R. Wager","",""],
        ["1929","Birch Tree Sidle","","East Peak, Lliwedd"],
        ["","Jack Longland, G.L. Trevelyan","",""],
        ["1929","Geography Climb","","Idwal Slabs"],
        ["","F.R.G. Chew, Miss Maud Gordon, R.C. Wakefield","",""],
        ["","The name is only readily intelligible to gentlemen of Trinity, where Sir Christopher's Wren's Library is adorned with four large female figures on the parapet, by some supposed to be Faith, Hope, Charity, and - she with the globe - Geography!","",""],
        ["1930, Easter","Javelin Blade","E1 5b","Holly Tree Wall, Idwal"],
        ["","Jack L. Longland","",""],
        ["","An outstanding lead that stood as the most difficult piece of Welsh climbing for many years, though few were aware of it. 'Quite frankly I'd lost my way. I'd come to the famous thread belay at the end of the first pitch of the normal route (Javelin Buttress VS), and I didn't know that the route ought to go right. I was a pole vaulter, which I think gives you pretty strong fingers, and I remember the pull-out onto the actual blade of the javelin was very strenuous; though not dangerous I had a belay about 40 feet below me'.","",""],
        ["1930","Lean Man's Superdirect","VS 4c","Black Rocks"],
        ["","Alf Bridge, Ivan Waller, Jack Longland","",""],
        ["","Waller considered a lead of the route to be unjustifiable and consequently the route was left un-recorded and un-named for 15 years. It was repeated (in 1945), by Peter Harding who, thinking it to be a new route, gave the route its name.","",""],
        ["1930","Bengal Buttress","HVS 4c","The Roaches"],
        ["","Ivan Waller","",""],
        ["","Some characteristic holes near the left-hand corner mark the start and are followed to a small but good ledge. This is passed in favour of a higher ledge which is followed to the right with increasing respect. The improving angle deludes one into anticipating some relief, but in actual fact the sharp corner above provides an awkward and exposed finish' - 1951 guidebook.","",""],
        ["1931, 9 Jul","Youth Crack","Diff","Nant yr Ogof, Ogwen"],
        ["","J.M. Edwards, C.H.S.R. Palmer","",""],
        ["1931, 10 Jul","Square Chimney Buttress","Severe","East Buttress, Glyder Fach"],
        ["","C.H.S.R. Palmer, S.B. Darbishire","",""],
        ["1931, 13 Jul","Llyn","HS 4a","Clogwyn y Tarw, Ogwen"],
        ["","C.H.S.R. Palmer, J.M. Edwards","",""],
        ["1931, 13 Jul","East Wall Girdle","VS","Idwal"],
        ["","J.M. Edwards, C.H.S.R. Palmer","",""],
        ["","First climbed in boots.","",""],
        ["1933, 23 Jul","Hothouse Crack","VDiff","Clogwyn y Geifr, Ogwen"],
        ["","J.M. Edwards, C.H.S.R. Palmer","",""],
        ["1933, 24 Jul","Devil's Pipes","HS","Clogwyn y Geifr"],
        ["","J.M. Edwards, C.H.S.R. Palmer","",""],
        ["","Palmer climbed the lower tower later that year.","",""],
        ["1935, 16 Jun","Flat Chimney","",""],
        ["","J.M. Edwards, C.H.S.R. Palmer","",""],
        ["1935, 25 Jun","Steep Wall","VDiff","Gallt yr Ogof, Ogwen"],
        ["","C.H.S.R. Palmer","",""],
        ["1936","Javelin Gully Direct Finish","HS","Idwal"],
        ["","Jack Longland","",""],
        ["1937, 9 Aug","Bivouac Buttress","Diff","Craig Lloer, Carneddau"],
        ["","C.H.S.R. Palmer","",""],
        ["1937, 11 Aug","Gnat's Gnose","Severe","Gallt yr Ogof, Ogwen"],
        ["","C.H.S.R. Palmer, J.A.B. Gray","",""],
        ["1937, 13 Aug","First Trinity Groove","VDiff","Craig Lloer, Carneddau"],
        ["","C.H.S.R. Palmer, J.A. Ingham","",""],
        ["1937, 13 Aug","Chimney Buttress","Diff","Craig Lloer"],
        ["","J.A. Ingham, C.H.S.R. Palmer","",""],
        ["1937, 20 Aug","Second Trinity Groove","Severe","Craig Lloer"],
        ["","C.H.S.R. Palmer, J.H. Buzzard","",""],
        ["1937, 23 Aug","Fence Climb","VDiff","Gallt yr Ogof, Ogwen"],
        ["","J.H. Buzzard, C.H.S.R. Palmer","",""],
        ["1944, 26 Aug","Skyline Chimney","Diff","Craig yr Ysfa, Carneddau"],
        ["","C.H.S.R. Palmer, J.M. Bechervaise","",""],
        ["1944, 30 Aug","The Overhangs","VS","Gallt yr Ogof, Ogwen"],
        ["","J.M. Bechervaise, C.H.S.R. Palmer","",""],
        ["","The variation was added much later, 18th September 1977, by Palmer. 'Climbed alone, and as an elderly gent of my advanced age (72), I found some of the moves very difficult and the exposure considerable. But it amused me and might amuse a few others of my vintage'.","",""],
        ["1944, 30 Aug","Crack and Wall","VDiff","Gallt yr Ogof, Ogwen"],
        ["","J.M. Bechervaise, C.H.S.R. Palmer","",""],
        ["1944, 30 Aug","Airy Corner","Diff","Gallt yr Ogof, Ogwen"],
        ["","C.H.S.R. Palmer, J.M. Bechervaise","",""],
        ["1944, 6 Sep","Giant's Steps Buttress","VDiff","Bristly Ridge, Ogwen"],
        ["","C.H.S.R. Palmer, J.M. Bechervaise","",""],
        ["1944, 6 Sep","Two Tower Buttress","VDiff","Bristly Ridge"],
        ["","C.H.S.R. Palmer, J.M. Bechervaise","",""],
        ["1944, 6 Sep","Great Tower Buttress","Severe","Bristly Ridge"],
        ["","C.H.S.R. Palmer","",""],
        ["1944, 10 Sep","The Chateau","Severe","Bristly Ridge"],
        ["","C.H.S.R. Palmer, J.M. Bechervaise, J.P. Walker and J.B. Williamson","",""],
        ["1950, Sum","Uncle's Chimney","Very Difficult","Ben Alder"],
        ["","CUMC Party","",""],
        ["1950, Sum","Left-Hand Chimney","Severe","Ben Alder"],
        ["","CUMC Party","",""],
        ["1952, 10 Jun","Bloody Slab","E3 5b","Clogwyn Du'r Arddu"],
        ["","J. Streetly (1 P.A.)","",""],
        ["","Also previously known as Red Slab. The rest of the party were unable to follow. The hardest slab in Wales at the time and only Streetly's second climb on the cliff. One peg runner was inserted after 70 feet of climbing!","",""],
        ["1954, 13 Jun","Sickle","VS","Trilleachan slabs, Glen Etive"],
        ["","Eric D.G. Langmuir, M. J. O'Hara, J. A. Mallinson","",""],
        ["1954 14 Jun","Spartan Slab","VS","Trilleachan slabs, Glen Etive"],
        ["","Eric D.G. Langmuir, M. J. O'Hara, J. A. Mallinson (3 P.A.)","",""],
        ["","Rather better than their first route, a genuine classic.","",""],
        ["1955, June","North-Eastern Grooves","VS","The Minus Face, Ben Nevis"],
        ["","R.O. Downes, M.J. O'Hara, Eric. D.G. Langmuir.","",""],
        ["","Climbed over 2 days with one PA, climbed free on 11 Jun 1960 by Downes O'Hara and Prestige","",""],
        ["1956, 11 June","Minus One Direct","HVS","The Minus Face, Ben Nevis"],
        ["","R.O.Downes, M.J. O'[Hara, M. Prestige (1 P.A.)","",""],
        ["1956, 30 Aug","Centurion","HVS","Carn Dearg, Ben Nevis"],
        ["","Don D. Whillans, R.O. Downes.","",""],
        ["1956, 1 Sep","The Shield","","Carn Dearg, Ben Nevis"],
        ["","Don D. Whillans, R.O. Downes","",""],
        ["1957, 21 Jun","The Ruritanian Climb","Severe","Garadh Na Ciste, Ben Nevis"],
        ["","CUMC Party","",""],
        ["1967, May","The Mushroom","VS","Craig-y-Rhaedr, Wales"],
        ["","M.R. Sinker, R.J. Isherwood (AL)","",""],
        ["1967, May","The Lobster","VS","Hen Cloud, Peak District"],
        ["","M.J. Guilliard, R. Whittacker","",""],
        ["1967, Jun","The Sewer","HVS","Craig-y-Rhaedr, Wales"],
        ["","M. Boysen, R.J. Isherwood (AL)","",""],
        ["1967, Jun","Kaleidoscope","VS","Carnmore Crag"],
        ["","G. Macnair, R. Jones (AL)","",""],
        ["1967, Jun","Connie-onnie","VS","Carnmore Crag"],
        ["","R. Jones, G. Macnair (AL)","",""],
        ["1967, Jun","The Sword","VS","Carnmore Crag"],
        ["","R.J. Isherwood, E. Birch","",""],
        ["1967, Jun","Penny Lane","VS","Carnmore Crag"],
        ["","E. Birch, R.J. Isherwood (AL)","",""],
        ["1967, Jun","Strawberry Fields","VS","Carnmore Crag"],
        ["","G. Macnair, R. Jones (AL)","",""],
        ["1967, Jun","Trampoline","VS","Carnmore Crag"],
        ["","R. Jones, G. Macnair (AL)","",""],
        ["1967, Jun","The Cracks","VS","Carnmore Crag"],
        ["","E. Birch, R.J. Isherwood (AL)","",""],
        ["1967, Jun","Compensation","Severe","A'Mhaighdean"],
        ["","R.J. Isherwood, E. Birch (AL)","",""],
        ["1967, Jul","The Curate's Egg","VS","Clogwyn-y-Ddysgl"],
        ["","R.J. Isherwood, C.H. Taylor (AL)","",""],
        ["1967, Jul","Hydra","VS","Esk Buttress, Lakes"],
        ["","R.J. Isherwood, C.H. Taylor (AL)","",""],
        ["1967, Aug","Aquila","Severe","Craig Na H'Iolaire, Torridon"],
        ["","J.L. Cardy, G. Halkyard","",""],
        ["1967, 22 Oct","The Cracks","HVS 5a","Gogarth, Anglesey"],
        ["","J.M. Kosterlitz, R.J. Isherwood (AL)","",""],
        ["1968, May","Mousetrap Zawn Girdle","E2 5b","Gogarth, Anglesey"],
        ["","M. Howells, J.M. Kosterlitz","",""],
        ["1969","Long John's Slab","E3 5c","Froggatt"],
        ["","Al Rouse (solo)","",""],
        ["","First free ascent.","",""],
        ["1970, Jun","Gemini","E4 5c","Clogwyn Du'r Arddu"],
        ["","A. Rouse, L. Dickinson","",""],
        ["","Only the leader's second visit to the cliff!","",""],
        ["1970, 19 Sep","Vagrant","VS","Coire an Lochain, Cairngorms"],
        ["","M.G. Geddes, H.M. Gillespie","",""],
        ["1970, 27 Dec","Fairy Godmother","III","Creag Megaidh"],
        ["","M.G. Geddes, N.C. Raynor","",""],
        ["1970, 28 Dec","Ugly Sister","III","Creag Megaidh"],
        ["","M.G. Geddes, N. C. Raynor","",""],
        ["1971, 15 Mar","Aphrodite","IV, 4","Three Gully Butress, Ben Nevis"],
        ["","M.G. Geddes, J.C. Higham","",""],
        ["1971, Mar","Positron","E5 6a","Gogarth, Anglesey"],
        ["","A.P. Rouse, P. Minks (5 P.A.)","",""],
        ["","Rouse flew off the route whilst Minks was rather more interested in the songs on the accompanying transistor radio.","",""],
        ["1971, Apr","Hadrian's Wall Direct","V, 5","Observatory Ridge, Ben Nevis"],
        ["","M.G. Geddes, G. E. Little (1 P.A.)","",""],
        ["1971, 21 Dec","Phoenix Buttress","III","Garbh Coire Mor, Braeriach"],
        ["","M.G. Geddes, J. S. Robinson","",""],
        ["1972, Mar","Right-Hand Route","VI, 6","Minus Face, Ben Nevis"],
        ["","R. Carrington, Al Rouse.","",""],
        ["1972, 11 Mar","South Pillar","IV, 4","Creagh Megaidh"],
        ["","R. Carrington, Al Rouse.","",""],
        ["1972, 1 Jul","The Sand Piper dir. Finish","HVS","The Stag Rocks, Cairngorms"],
        ["","M.G. Geddes, J.C. Higham","",""],
        ["1973, Jan","Nick the Neck","VDiff","Craig Cwrwgl, Ogwen"],
        ["","Nick J. Estcourt, C.T. Jones","",""],
        ["","'Much better than poncing back down those odious gullys'.","",""],
        ["1975, Wint","The Citadel, Winter Var","VI, 8","Shelter Stone crag, Cairngorms"],
        ["","Al Rouse, B. Hall","",""],
        ["1975, May","Aura","E2 5b","Craig yr Isfa, Carneddau"],
        ["","R. Carrington, Al Rouse, B.Hall","",""],
        ["","An utterly brilliant main pitch.","",""],
        ["1975, Jun 29","Head for Heights","E5 6b","Clogwyn Du'r Arddu"],
        ["","C.J. Phillips, N.J. Estcourt (4 P.A.)","",""],
        ["1976, Mar","Left Edge Route","VI, 5","Gardyloo Buttress, Ben Nevis"],
        ["","R. Carrington, Al Rouse. (1 P.A.)","",""],
        ["1976","Neutrino","E1 5b","Gogarth, Anglesey"],
        ["","A.P. Rouse, B. Hall","",""],
        ["1977, 29 Dec","Sickle","V, 5","Observatory Ridge, Ben Nevis"],
        ["","M.G. Geddes, B.P. Hall","",""],
        ["1978, 21 Jan","Albatross","VII, 6","Indicator Wall, Ben Nevis"],
        ["","M.G. Geddes, C. Higgins","",""],
        ["1978, 4 Feb","Five Finger Discount","IV, 4","Two Gully Buttress, Ben Nevis"],
        ["","M.G. Geddes, C. Higgins","",""],
        ["1978, 11 Feb","Shot in the Dark","V, 5","Indicator Wall, Ben Nevis"],
        ["","M.G. Geddes, Al Rouse","",""],
        ["1978, 12 Feb","Route II Direct","VI, 6","Carn Dearg Buttress, Ben Nevis"],
        ["","M.G. Geddes, Al Rouse","",""],
        ["","*'Then the headlamp came off. The wire tangled with slings, the slings tangled with the axe, and panic threatened.' Despite an early start the climb was finished in the dark. Three pegs for tension were used, but an important ascent and probably Geddes finest contribution to Nevis.","",""],
        ["1978, 25 Mar","The Six-track Mono Blues","II","Meall Gorm, Applecross"],
        ["","M.G. Geddes, B.P. Hall, A. McIntyre, J. Porter","",""],
        ["1978, 8 Apr","Burrito's Groove","IV, 5","Two Gulley Buttress, Ben Nevis"],
        ["","M.G. Geddes, C. Higgins","",""],
        ["1978, 14 Apr","Galactic Hitchhiker","VI, 5","Observatory Ridge, Ben Nevis"],
        ["","M.G. Geddes, C. Higgins","",""],
        ["","A tied-off knifeblade was used to enter the corner at the start of pitch 4. 'Up and down I went on that awful peg, searching for adequate holds until my strength and warmth were almost gone. Finally I found enough...'","",""],
        ["1978, 22 Apr","Lepton","E2 6b","Curbar Edge"],
        ["","Al Rouse, Nick Colton, Rab Carrington","",""],
        ["","All soloed: later claimed by Ron Fawcett as Kaffleout.","",""],
        ["1982-83","Groat (n\ufffde Al's Ar\ufffdte)","E1 6b","Burbage North"],
        ["","Al Rouse, Richard Haszko","",""],
        ["1983, 7 Oct","Nicotine Stain","E1 6b","Burbage North"],
        ["","Al Rouse (solo)","",""],
        ["1983, 4 Dec","Dark Water","E3 6b","Stanage"],
        ["","Al Rouse, 'others'","",""],
        ["1983, 6 Dec","Findus","HVS 5b","Millstone Edge"],
        ["","Al Rouse, Phil Burke","",""],
        ["1983, 7 Dec","Quality Street","E5 6b,6a","Millstone Edge"],
        ["","Al Rouse, Phil Burke (AL)","",""],
        ["1984, 15 Feb","Reagent","E5 6a","Stanage"],
        ["","Al Rouse (solo)","",""],
        ["1984, 3 Apr","Andy Pollitt's Jacket","E3 5c","Curbar Edge"],
        ["","Al Rouse (solo)","",""],
        ["","Top-roped first. Named in honour of Andy's new 'freebie' jacket.","",""],
        ["1984, Apr","Make it Snappy","E6 6c","Gardom's Edge"],
        ["","Neil Foster, Al Rouse","",""],
        ["1984, May","Green Line","HVS 5b","Stanage"],
        ["","Al Rouse (solo)","",""],
        ["1984, Sep","Regret","E2 5c","Stanage"],
        ["","Al Rouse, Neil Foster","",""],
        ["1984, 13 Oct","Blind Date","E5 7a","Burbage North"],
        ["","Al Rouse","",""],
        ["","Al's finest hour. Eventually climbed in sections after many attempts. Soon after the first ascent, the boulder which just allowed a desperate 'splits' bridge to begin the route strangely migrated towards the crag making the start easier. This boulder has now gone altogether, thereby making the start appallingly difficult.","",""],
        ["1984, 13 Oct","Led A Dance","HVS 5b","Stanage"],
        ["","Chris Plant, Brian Davison, Alan Dance","",""],
        ["","Note the name of the third man.","",""],
        ["1984, 14 Oct","Rockhopper","E1 5c","Lawrencefield"],
        ["","B. Davison, S. Biskill","",""],
        ["1984, 24 Nov","Error of Judgement","E1 5a","Cilan Head, Lleyn Peninsula"],
        ["","R. Jones, B. Davison","",""],
        ["1984, 16 Dec","Fast and Bulbous","E2 5b","Park Banks Crag, Lower Churnet"],
        ["","Brian Davison, Richard Jones, Neil Horn","",""],
        ["1984, 26 Dec","Tough Guy","V","Tough-Brown Face, Lochnagar"],
        ["","A. Nisbet, B. Davison","",""],
        ["","First Winter Ascent","",""],
        ["1984","The Wild and the Innocent","E2 5b","Kinder North Edge"],
        ["","Steve Payne, Robin Pakeman","",""],
        ["1984","Uncertain Smile","E1 5b","Crag Caerfai, N. Pembroke"],
        ["","Richard Jones","",""],
        ["1984","Sea Creature","E4 6a","Millstone Edge"],
        ["","Al Rouse, Andy Bailey","",""],
        ["1985, 27 Apr","Friendless","HVS 5a,4b","Cilan Head, Lleyn Peninsula"],
        ["","B. Davison, Ray Delaney","",""],
        ["1985, 28 Apr","Livingston I Presume","VS 4c,4b","Tyn Towyn Quarries, Lleyn Peninsula"],
        ["","B. Davison, R. Delaney","",""],
        ["1985, 28 Apr","Horus","VS 4c","Tyn Towyn Quarries, Lleyn Peninsula"],
        ["","B. Davison, R. Delaney","",""],
        ["1985, 28 Apr","Jivin Jaki","VS 4c","Tyn Towyn Quarries, Lleyn Peninsula"],
        ["","R. Delaney, B. Davison","",""],
        ["1985, 7 May","Wash and Brush Up","E1 6b","Millstone Edge"],
        ["","Al Rouse (solo)","",""],
        ["1985, 12 May","African Herbs","E2 5c","Stanage"],
        ["","Al Rouse, Richard Hazsko","",""],
        ["1985, Jun","Tower Block","E3 6b","Stanage"],
        ["","Al Rouse (unseconded)","",""],
        ["1985, Aug","Rockers","E1 5c","Burbage North"],
        ["","Al Rouse, Steve Sustad","",""],
        ["1985","Al","E4 5c","Stanage"],
        ["","Al Rouse, Steve Bancroft","",""],
        ["1986, 6 Jul","Seal Clubbing","E2 5c","Dyers Lookout, Culm Coast"],
        ["","B. Davison, R. Jones, A. Smith","",""],
        ["1986, 20 Jul","Sunday Stroll","Severe","Tyn Towyn Quarries, Lleyn Peninsula"],
        ["","B. Davison, A. Smith, Alan Dick","",""],
        ["1986, 26 Jul","All Your Seasick Boaties, They Are Rowing Home","Hard Difficult","Crystal Slabs, Pembroke"],
        ["","Harry Adshead, Lewis Grundy, Pete Walker","",""],
        ["1986, 27 Jul","Time Flies By","E4 5c","Park Banks Crag, Lower Churnet"],
        ["","Brian Davison, Richard Jones","",""],
        ["1986, 9 Aug","Twrch Trwyth","HVS 5a","Penbwchdy"],
        ["","R. Jones, I. Hamilton","",""],
        ["1986, 16 Aug","The Necromancer","E3 5c","Tyn Towyn Quarries, Lleyn Peninsula"],
        ["","B. Davison, A. Smith","",""],
        ["1986, 16 Aug","White Magic Dust","HVS 5b","Tyn Towyn Quarries, Lleyn Peninsula"],
        ["","A. Smith, B. Davison","",""],
        ["1986, 20 Sep","Friends Essential","E1 5b","Chasm East, Isle of Man"],
        ["","B. Davison, A. Smith","",""],
        ["1986, 20 Sep","Scooper","VS 4b","Chasm East, Isle of Man"],
        ["","B.Davison, A. Smith","",""],
        ["1986, 20 Sep","In the Beginning","E2 5b","Chasm East, Isle of Man"],
        ["","B. Davison, A. Smith","",""],
        ["1986, 20 Sep","Moonburn","HVS 4c","Chasm East, Isle of Man"],
        ["","B. Davison, A. Smith","",""],
        ["1986, 21 Sep","Antartic Caterpillar","E1 5c","Bulgham Bay, Isle of Man"],
        ["","B. Davison, A. Smith","",""],
        ["1986, 27 Sep","Headless Donkey","E2 5b","Pembroke"],
        ["","","",""],
        ["","Brian Davison, Andy Smith","",""],
        ["1986, 27 Sep","Gin and Woodbines","HVS 5b","Pembroke"],
        ["","Richard Jones, Ian Hamilton","",""],
        ["1986, 12 Oct","Anorexic Weirdo","E6 6c","Tyn Towyn Quarries, Lleyn Peninsula"],
        ["","B. Davison, R. Jones, A. Smith","",""],
        ["1986, Sum","Agrajat","E5 6a","Glen Cova"],
        ["","Chris Cracknell","",""],
        ["1986, Sum","Headspread","E4 6a","Glen Cova"],
        ["","Chris Cracknell","",""],
        ["1986, Sum","Catwalk","E1 5a","Glen Cova"],
        ["","Chris Cracknell","",""],
        ["1987, 17 Jan","Manx Wall","V","Clogwyn Du, Penbwchdy"],
        ["","Brian Davison, Gordon Scott","",""]

]
}

router.get('/routes', function(req, res, next) {
    res.json({
        head: firstAscents.head,
        body: firstAscents.body,
    });
});

router.get('/whatsapp', function(req, res) {
    res.json(req.isAuthenticated() ? process.env.WHATSAPP : 'https://www.cumc.org.uk/login')
    // Hide whatsapp link from non-members :)
});

module.exports = router;